### ISSUE TITLE
YustTextField showSelected not consistent

### ISSUE THREAD

**Issue by philthefox** [univelop/yust_ui#57]
The property 'showSelected' in the class YustTextField should also affect icons if set to false. If set to true, it currently affects only the properties 'label' and 'prefixIcon'.

![Image](https://user-images.githubusercontent.com/43797286/211650071-026e8aa6-9d8a-4bf0-a120-39812ca369ba.jpg)

**Comment by janneskoehler** [comment]
We do not need the property `showSelected`.
